import type { ComponentType } from 'react';

export type ToolLoader = () => Promise<{ default: ComponentType }>;

/** slug → dynamic import ของ Tool.tsx (code-split ต่อเครื่องมือ) */
export const toolLoaders: Record<string, ToolLoader> = {
  'pdf-merge': () => import('./documents/pdf-merge/Tool'),
  'pdf-extract': () => import('./documents/pdf-extract/Tool'),
  'pdf-remove-pages': () => import('./documents/pdf-remove-pages/Tool'),
  'pdf-rotate': () => import('./documents/pdf-rotate/Tool'),
  'images-to-pdf': () => import('./documents/images-to-pdf/Tool'),
  'excel-to-csv': () => import('./documents/excel-to-csv/Tool'),
  'csv-to-excel': () => import('./documents/csv-to-excel/Tool'),
  'word-to-text': () => import('./documents/word-to-text/Tool'),
  'image-compress': () => import('./images/image-compress/Tool'),
  'image-resize': () => import('./images/image-resize/Tool'),
  'image-convert': () => import('./images/image-convert/Tool'),
  'image-rotate': () => import('./images/image-rotate/Tool'),
  'thai-income-tax': () => import('./finance/thai-income-tax/Tool'),
  'loan-installment': () => import('./finance/loan-installment/Tool'),
  'net-salary': () => import('./finance/net-salary/Tool'),
  'vat-wht': () => import('./finance/vat-wht/Tool'),
  'compound-interest': () => import('./finance/compound-interest/Tool'),
  'baht-text': () => import('./text/baht-text/Tool'),
  'word-count': () => import('./text/word-count/Tool'),
  'thai-numerals': () => import('./text/thai-numerals/Tool'),
  'text-lines': () => import('./text/text-lines/Tool'),
  'thai-id-check': () => import('./text/thai-id-check/Tool'),
  'age-days': () => import('./date/age-days/Tool'),
  'thai-year-convert': () => import('./date/thai-year-convert/Tool'),
  'thai-holidays': () => import('./date/thai-holidays/Tool'),
  'promptpay-qr': () => import('./qr/promptpay-qr/Tool'),
  'qr-generator': () => import('./qr/qr-generator/Tool'),
  'qr-reader': () => import('./qr/qr-reader/Tool'),
  'json-formatter': () => import('./dev/json-formatter/Tool'),
  'date-add': () => import('./date/date-add/Tool'),
  'work-tenure': () => import('./finance/work-tenure/Tool'),
  'ot-calculator': () => import('./finance/ot-calculator/Tool'),
  'land-unit-convert': () => import('./land/land-unit-convert/Tool'),
  'land-price': () => import('./land/land-price/Tool'),
  'fuel-cost': () => import('./daily/fuel-cost/Tool'),
  'profit-margin': () => import('./business/profit-margin/Tool'),
  'selling-price': () => import('./business/selling-price/Tool'),
  'social-security': () => import('./finance/social-security/Tool'),
  'severance-pay': () => import('./finance/severance-pay/Tool'),
  'wht-calculator': () => import('./finance/wht-calculator/Tool'),
  'home-loan': () => import('./loan/home-loan/Tool'),
  'car-loan': () => import('./loan/car-loan/Tool'),
  'credit-card-debt': () => import('./loan/credit-card-debt/Tool'),
  'flat-effective-rate': () => import('./loan/flat-effective-rate/Tool'),
  'electricity-bill': () => import('./daily/electricity-bill/Tool'),
  'shop-profit': () => import('./business/shop-profit/Tool'),
};
